using System.Text;
using VulnRadar.Parsers;
using VulnRadar.State;

namespace VulnRadar.Report;

/// <summary>Report generation for VulnRadar.</summary>
public static class ReportWriter
{
    /// <summary>Write a GitHub-renderable Markdown report.</summary>
    public static void WriteMarkdownReport(
        string path,
        List<RadarItem> items,
        string? stateFile = null)
    {
        Directory.CreateDirectory(System.IO.Path.GetDirectoryName(path) ?? ".");

        var total = items.Count;
        var watchHits = items.Count(i => i.WatchlistHit);
        var kevCount = items.Count(i => i.ActiveThreat);
        var patchCount = items.Count(i => i.InPatchthis);
        var criticalPatchWatch = items.Count(i => i.InPatchthis && i.WatchlistHit);

        var top = items.OrderByDescending(CveParsers.RiskSortKey).Take(200).ToList();
        foreach (var i in top)
            i.Bucket = CveParsers.RiskBucket(i);

        var criticalItems = items.Where(i => i.IsCritical)
            .OrderByDescending(CveParsers.RiskSortKey)
            .Take(25)
            .ToList();

        var recentChanges = BuildRecentChanges(stateFile);
        var generatedAt = DateTime.UtcNow.ToString("o");

        var sb = new StringBuilder();
        sb.AppendLine("# 🛡️ VulnRadar — Vulnerability Intelligence Report");
        sb.AppendLine();
        sb.AppendLine($"> Generated: {generatedAt}");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("## 📊 Summary");
        sb.AppendLine();
        sb.AppendLine("| Metric | Count |");
        sb.AppendLine("|--------|-------|");
        sb.AppendLine($"| Total CVEs | {total} |");
        sb.AppendLine($"| 🎯 Watchlist Hits | {watchHits} |");
        sb.AppendLine($"| ⚠️ CISA KEV | {kevCount} |");
        sb.AppendLine($"| 🔥 PatchThis | {patchCount} |");
        sb.AppendLine($"| 🚨 Critical (exploit + watchlist) | {criticalPatchWatch} |");
        sb.AppendLine();

        if (recentChanges.Count > 0)
        {
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine("## 📅 Recent Changes (Last 7 Days)");
            sb.AppendLine();
            sb.AppendLine("| Date | CVE | Change |");
            sb.AppendLine("|------|-----|--------|");
            foreach (var (date, cveId, changeType) in recentChanges)
            {
                sb.AppendLine($"| {date} | [{cveId}](https://www.cve.org/CVERecord?id={cveId}) | {changeType} |");
            }
            sb.AppendLine();
        }

        if (criticalItems.Count > 0)
        {
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine("## 🔴 Critical Findings (Top 25)");
            sb.AppendLine();
            sb.AppendLine("| CVE | EPSS | CVSS | KEV | Exploit | Description |");
            sb.AppendLine("|-----|------|------|-----|---------|-------------|");
            foreach (var item in criticalItems)
            {
                var desc = item.Description.Length > 80
                    ? item.Description[..80].Replace("|", "\\|") + "..."
                    : item.Description.Replace("|", "\\|");
                var kev = item.ActiveThreat ? "🔴" : "⚪";
                var patch = item.InPatchthis ? "🟠" : "⚪";
                sb.AppendLine(
                    $"| [{item.CveId}](https://www.cve.org/CVERecord?id={item.CveId}) | " +
                    $"{CveParsers.FormatEpss(item.ProbabilityScore)} | " +
                    $"{CveParsers.FormatCvss(item.CvssScore)} | {kev} | {patch} | {desc} |");
            }
            sb.AppendLine();
        }

        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("## 📋 Top CVEs by Risk Score");
        sb.AppendLine();
        sb.AppendLine("| CVE | Risk | EPSS | CVSS | KEV | Watchlist | Description |");
        sb.AppendLine("|-----|------|------|------|-----|-----------|-------------|");

        foreach (var item in top)
        {
            var desc = item.Description.Length > 60
                ? item.Description[..60].Replace("|", "\\|") + "..."
                : item.Description.Replace("|", "\\|");
            var kev = item.ActiveThreat ? "✅" : "❌";
            var watch = item.WatchlistHit ? "✅" : "❌";
            sb.AppendLine(
                $"| [{item.CveId}](https://www.cve.org/CVERecord?id={item.CveId}) | " +
                $"{item.Bucket ?? CveParsers.RiskBucket(item)} | " +
                $"{CveParsers.FormatEpss(item.ProbabilityScore)} | " +
                $"{CveParsers.FormatCvss(item.CvssScore)} | {kev} | {watch} | {desc} |");
        }

        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("_Generated by [VulnRadar](https://github.com/ALange/VulnRadar) (C# Edition)_");

        var tmp = path + ".tmp";
        File.WriteAllText(tmp, sb.ToString());
        File.Move(tmp, path, overwrite: true);
    }

    private static List<(string Date, string CveId, string ChangeType)> BuildRecentChanges(string? stateFile)
    {
        if (stateFile == null || !File.Exists(stateFile))
            return new List<(string, string, string)>();

        try
        {
            var state = new StateManager(stateFile);
            var sevenDaysAgo = DateTime.UtcNow.AddDays(-7);
            var recent = new List<(string Date, string CveId, string ChangeType)>();

            foreach (var (cveId, firstSeen) in state.GetAllTracked())
            {
                if (firstSeen == null) continue;
                if (!DateTime.TryParse(firstSeen, out var dt)) continue;
                if (dt < sevenDaysAgo) continue;

                // Use snapshot to determine change type
                var snap = state.GetSnapshot(cveId);
                string changeType;
                if (snap?.ActiveThreat == true) changeType = "🔴 In CISA KEV";
                else if (snap?.InPatchthis == true) changeType = "🟠 In PatchThis";
                else if (snap?.IsCritical == true) changeType = "🔥 Critical";
                else changeType = "🆕 New";

                recent.Add((dt.ToString("MMM dd"), cveId, changeType));
            }

            return recent.OrderByDescending(r => r.Date).ToList();
        }
        catch
        {
            return new List<(string, string, string)>();
        }
    }
}
